# Generated by Django 4.1.2 on 2023-01-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='index',
        ),
    ]
